apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outerspace-go
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/speedscale/outerspace-go
    targetRevision: HEAD
    path: k8s
    kustomize:
      namespace: spd-demo-outerspace
  destination:
    server: https://kubernetes.default.svc
    namespace: spd-demo-outerspace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true