#!/usr/bin/env bash

set -eou pipefail

SERVER_URL=${SERVER_URL:-"localhost:8080"}
loginToken=""
rsaToken=""

echo $SERVER_URL

RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

login() {
    echo -e "${RED}Getting login token ${NC}"
    loginToken=$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "admin", "password": "pass" }' "${SERVER_URL}/login" | jq -r .access_token)
    echo -e "${RED}Login token is ${loginToken}${NC}"
    echo
}

rsaToken() {
    echo -e "${RED}Getting RSA token ${NC}"
    rsaToken=$(curl -s -X POST -H "Content-Type: application/json" -d '{"username": "admin", "password": "pass" }' "${SERVER_URL}/rsaToken" | jq -r .access_token)
    echo -e "${RED}RSA token is ${rsaToken}${NC}"
    echo
}

launches() {
    echo -e "${BLUE}Getting launches ${NC}"
    curl -s -X GET -H "Authorization: Bearer ${loginToken}" "${SERVER_URL}/spacex/launches"
    echo
    echo
}

random-ship() {
    echo -e "${BLUE}Getting random ship ${NC}"
    curl -s -X GET -H "Authorization: Bearer ${loginToken}" "${SERVER_URL}/spacex/ship"
    echo
    echo
}

ship() {
    ships=("618fad7e563d69573ed8caa9" "614251b711a64135defb3654" "5ea6ed30080df4000697c916")
    id=${ships[ $RANDOM % ${#ships[@]} ]}

    echo -e "${BLUE}Getting ship ${id} ${NC}"
    curl -s -X GET -H "Authorization: Bearer ${loginToken}" "${SERVER_URL}/spacex/ship/${id}"
    echo
    echo
}

interest() {
    echo -e "${BLUE}Getting max interest rate security ${NC}"
    curl -s -X GET -H "Authorization: Bearer ${rsaToken}" "${SERVER_URL}/treasury/max_interest"
    echo
    echo
}

random-sleep () {
    sleep $(( RANDOM % 3 ))
}

i=0
while true; do
    if [[ $((i % 5)) == 0 ]]; then
        login
        rsaToken
    fi

    launches
    random-sleep

    random-ship
    random-sleep

    ship
    random-sleep

    interest
    random-sleep
    i=$((i+1))
done
