---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-weather
  labels:
    app: csharp-weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-weather
  template:
    metadata:
      labels:
        app: csharp-weather
    spec:
      containers:
        - name: csharp-weather
          image: gcr.io/speedscale-demos/csharp-weather:v1.2.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
            - name: ASPNETCORE_URLS
              value: "http://+:8080"
            - name: OPENWEATHER_API_KEY
              value: "b1e641006d0b095192f4e5dd0932f93d"
            - name: OPENWEATHER_CITY
              value: "Cebu City"
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: csharp-weather
  labels:
    app: csharp-weather
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: csharp-weather
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: csharp-client
  labels:
    app: csharp-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csharp-client
  template:
    metadata:
      labels:
        app: csharp-client
    spec:
      containers:
        - name: csharp-client
          image: gcr.io/speedscale-demos/csharp-client:v1.2.4
          imagePullPolicy: Always
          env:
            - name: SERVER_URL
              value: "http://csharp-weather"
            - name: DELAY_MS
              value: "5000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
