spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:auth_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${MYSQL_USERNAME:auth_user}
    password: ${MYSQL_PASSWORD:secure_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    
server:
  port: 8080
  
jwt:
  secret: ${JWT_SECRET:your-secret-key-here-please-change-in-production}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-token-expiration: ${REFRESH_TOKEN_EXPIRATION:604800000}
  
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      
logging:
  level:
    com.example.auth: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE