spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/banking_app
    username: transactions_service_user
    password: transactions_service_pass
  
  flyway:
    url: jdbc:postgresql://postgres:5432/banking_app
    user: transactions_service_user
    password: transactions_service_pass

# External Service URLs for Docker
accounts:
  service:
    url: http://accounts-service:8080

# OpenTelemetry Configuration for Docker
otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://jaeger:4318
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  propagation:
    type: w3c