source 'https://rubygems.org'

gem 'sinatra', '~> 4.2'
gem 'sinatra-contrib', '~> 4.2'
gem 'pg', '~> 1.5'
gem 'httparty', '~> 0.21'
gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.2'
gem 'json', '~> 2.7'
gem 'rack', '~> 3.2', '>= 3.2.3'
gem 'jwt', '~> 2.7'

group :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test', '~> 2.1'
end
