apiVersion: apps/v1
kind: Deployment
metadata:
  name: ruby-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ruby-server
  template:
    metadata:
      labels:
        app: ruby-server
    spec:
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.35
          command:
          - sh
          - -c
          - |
            until nc -z postgres-service 5432; do
              echo "Waiting for PostgreSQL..."
              sleep 2
            done
            echo "PostgreSQL is ready!"
      containers:
        - name: ruby-server
          image: gcr.io/speedscale-demos/ruby-api:v1.2.3
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: http
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: ruby-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: ruby-config
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: ruby-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: ruby-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 15
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
