apiVersion: v1
kind: Service
metadata:
  name: ruby-server
  labels:
    app: ruby-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app: ruby-server
