apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../../base/auth-server

namespace: java-auth

labels:
  - pairs:
      app.kubernetes.io/variant: auth-only
    includeSelectors: true

patches:
  - target:
      kind: Deployment
      name: java-auth
    patch: |-
      - op: remove
        path: /spec/template/spec/initContainers