apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
  labels:
    app: java-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
        - name: java-server
          image: gcr.io/speedscale-demos/java-server:1.0.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: REQUEST_TAG
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-server
  labels:
    app: java-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: java-server
