apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-server
  labels:
    app: java-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-server
  template:
    metadata:
      labels:
        app: java-server
    spec:
      containers:
        - name: java-server
          image: gcr.io/speedscale-demos/java-server:1.0.0
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          ports:
            - containerPort: 8080
              name: http
          env:
          - name: REQUEST_TAG
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: java-server
  labels:
    app: java-server
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: java-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-client
  labels:
    app: java-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-client
  template:
    metadata:
      labels:
        app: java-client
    spec:
      containers:
        - name: java-client
          image: registry.gitlab.com/gitlab-ci-utils/curl-jq
          imagePullPolicy: Always
          command:
          - bash
          - -c
          - /client
          env:
          - name: SERVER_URL
            value: java-server
          volumeMounts:
          - mountPath: "/client"
            name: "script"
            subPath: client
          resources:
            requests:
              cpu: 10m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 100Mi
      volumes:
      - name: script
        configMap:
          name: client-script
          defaultMode: 0777
