apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-auth
  namespace: java-auth
  labels:
    app: java-auth
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: java-auth
  template:
    metadata:
      labels:
        app: java-auth
        version: v1
    spec:
      initContainers:
      - name: wait-for-mysql
        image: busybox:1.35
        command: ['sh', '-c', 'until nc -z mysql-service 3306; do echo waiting for mysql; sleep 2; done;']
      containers:
      - name: java-auth
        image: gcr.io/speedscale-demos/java-auth:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        env:
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
        - name: JWT_SECRET
          value: "your-256-bit-secret-key-for-jwt-signing-in-production"
        envFrom:
        - configMapRef:
            name: auth-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 15"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30