apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_HOST: "mysql-service"
  MYSQL_PORT: "3306"
  init.sql: |
    CREATE DATABASE IF NOT EXISTS auth_db;
    USE auth_db;
    GRANT ALL PRIVILEGES ON auth_db.* TO 'auth_user'@'%';
    FLUSH PRIVILEGES;