apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: llm-simulation
  namespace: llm-simulation
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "120"
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: llm-simulation-frontend
                port:
                  number: 3000
