openapi: 3.0.3
info:
  title: Transactions Service
  description: API for managing financial transactions.
  version: 1.0.0
servers:
  - url: http://localhost:8083
    description: Local development server
paths:
  /transactions:
    get:
      summary: Get all transactions for the authenticated user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: A list of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TransactionResponse'
  /transactions/deposit:
    post:
      summary: Deposit funds into an account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DepositRequest'
      responses:
        '201':
          description: Deposit successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/withdraw:
    post:
      summary: Withdraw funds from an account
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WithdrawRequest'
      responses:
        '201':
          description: Withdrawal successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'
  /transactions/transfer:
    post:
      summary: Transfer funds between accounts
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransferRequest'
      responses:
        '201':
          description: Transfer successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionResponse'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    TransactionResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        fromAccountId:
          type: integer
          format: int64
          nullable: true
        toAccountId:
          type: integer
          format: int64
          nullable: true
        amount:
          type: number
        type:
          type: string
        timestamp:
          type: string
          format: date-time
    DepositRequest:
      type: object
      required:
        - accountId
        - amount
      properties:
        accountId:
          type: integer
          format: int64
        amount:
          type: number
    WithdrawRequest:
      type: object
      required:
        - accountId
        - amount
      properties:
        accountId:
          type: integer
          format: int64
        amount:
          type: number
    TransferRequest:
      type: object
      required:
        - fromAccountId
        - toAccountId
        - amount
      properties:
        fromAccountId:
          type: integer
          format: int64
        toAccountId:
          type: integer
          format: int64
        amount:
          type: number
