apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo
resources:
- ns.yaml
- base/gateway.yaml
- base/payment.yaml
- base/user.yaml
- jobs/configmap.yaml
- jobs/traffic.yaml
#patchesStrategicMerge:
#- patch/inject.yaml