apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: gateway
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - name: gateway
        image: nginx:1.27
        command: ["/bin/sh", "-c"]
        args:
        - |
          cat > /etc/nginx/conf.d/custom.conf <<'EOF'
          server {
            listen 8080;
            location /payment/ {
              proxy_pass http://payment/;
            }
            location /user/ {
              proxy_pass http://user/;
            }
            location /login {
              return 200 '{"Bearer accepted"}\n';
            }
            location /spacex/ {
              proxy_pass https://api.spacexdata.com/v4/;
              proxy_ssl_protocols TLSv1.2 TLSv1.3;
              proxy_ssl_server_name on;
              proxy_set_header Host api.spacexdata.com;
            }
          }
          EOF
          exec nginx -g 'daemon off;'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 512Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: gateway
