apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  replicas: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: nginx:1.27
        command: ["/bin/sh", "-c"]
        args:
        - |
          cat > /etc/nginx/conf.d/custom.conf <<'EOF'
          server {
            listen 8080;
            location / {
              default_type application/json;
              return 200 '{"status": "ok", "service": "payment", "version": "1.0"}\n';
            }
            location /providers {
              proxy_pass https://api.github.com/;
              proxy_ssl_protocols TLSv1.2 TLSv1.3;
              proxy_ssl_server_name on;
              proxy_set_header Host api.github.com;
              proxy_set_header User-Agent nginx-demo;
            }
            location /lookup {
              default_type application/json;
              return 200 '{"processing": {"errors": "none"}}\n';
            }
          }
          EOF
          exec nginx -g 'daemon off;'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 512Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: payment
