apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: nginx:1.27
        command: ["/bin/sh", "-c"]
        args:
        - |
          cat > /etc/nginx/conf.d/custom.conf <<'EOF'
          server {
            listen 8080;
            location / {
              default_type application/json;
              return 200 '{"user": {"name": "Matt"}}\n';
            }
            location /profile {
              default_type application/json;
              return 200 '{"reviews": {"summary": "One star. Very bad, would not recommend."}}\n';
            }
          }
          EOF
          exec nginx -g 'daemon off;'
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: "1"
            memory: 512Mi
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: user
