apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-auth
spec:
  replicas: 2
  template:
    spec:
      containers:
      - name: java-auth
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: staging-jwt-secret
              key: secret