spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/banking_app
    username: accounts_service_user
    password: accounts_service_pass
  
  flyway:
    url: jdbc:postgresql://postgres:5432/banking_app
    user: accounts_service_user
    password: accounts_service_pass

# OpenTelemetry Configuration for Docker
otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://jaeger:4318
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  propagation:
    type: w3c