spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/banking_app
    username: accounts_service_user
    password: accounts_service_pass
  
  flyway:
    url: jdbc:postgresql://postgres:5432/banking_app
    user: accounts_service_user
    password: accounts_service_pass

# OpenTelemetry Configuration for Docker
otel:
  exporter:
    jaeger:
      endpoint: http://jaeger:14250