# Example: k8s/base/kustomization.yaml
# Copy this to your app repo
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

commonLabels:
  app: your-app-name