version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: auth-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: auth_db
      MYSQL_USER: auth_user
      MYSQL_PASSWORD: secure_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DATABASE: auth_db
      MYSQL_USERNAME: auth_user
      MYSQL_PASSWORD: secure_password
      JWT_SECRET: your-secret-key-here-please-change-in-production
      JWT_EXPIRATION: 3600000
      REFRESH_TOKEN_EXPIRATION: 604800000
    depends_on:
      mysql:
        condition: service_healthy
        
  auth-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: auth-client
    restart: always
    environment:
      SERVER_URL: auth-service:8080
    depends_on:
      - auth-service
        
volumes:
  mysql-data: