apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: dotnet-orders
      app.kubernetes.io/instance: dotnet-orders
      app.kubernetes.io/part-of: dotnet-orders-system
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
