spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 30000
        response-timeout: 60s
  # Redis rate limiter configuration removed - not using rate limiting currently

server:
  port: 8080

# Service Discovery Configuration
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  accounts-service:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:8082}
  transactions-service:
    url: ${TRANSACTIONS_SERVICE_URL:http://localhost:8083}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:banking-app-super-secret-key-change-this-in-production-256-bit}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    com.banking.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

# OpenTelemetry Configuration
otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://localhost:4318
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  propagation:
    type: w3c

# Info endpoint
info:
  app:
    name: ${spring.application.name}
    description: Banking API Gateway
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
        
# Tracing
management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4317
    metrics:
      export:
        enabled: true
        step: 1m
        resource-attributes:
          service.name: ${spring.application.name}
          
# Logging
logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
    