spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Health check routes for direct access (higher priority with lower order)
        - id: user-service-health
          uri: ${services.user-service.url}
          order: -1
          predicates:
            - Path=/api/user-service/health
          filters:
            - RewritePath=/api/user-service/health, /actuator/health
        - id: accounts-service-health
          uri: ${services.accounts-service.url}
          order: -1
          predicates:
            - Path=/api/accounts-service/health
          filters:
            - RewritePath=/api/accounts-service/health, /actuator/health
        - id: transactions-service-health
          uri: ${services.transactions-service.url}
          order: -1
          predicates:
            - Path=/api/transactions-service/health
          filters:
            - RewritePath=/api/transactions-service/health, /actuator/health
            
        # Main service routes
        - id: user-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/user-service/**
          filters:
            - RewritePath=/api/user-service/(?<path>.*), /user/$\{path}
        - id: accounts-service
          uri: ${services.accounts-service.url}
          predicates:
            - Path=/api/accounts-service/**
          filters:
            - RewritePath=/api/accounts-service/(?<path>.*), /accounts/$\{path}
        - id: transactions-service
          uri: ${services.transactions-service.url}
          predicates:
            - Path=/api/transactions-service/**
          filters:
            - RewritePath=/api/transactions-service/(?<path>.*), /transactions/$\{path}
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 30000
        response-timeout: 60s
  # Redis rate limiter configuration removed - not using rate limiting currently

server:
  port: 8080

# Service Discovery Configuration
services:
  user-service:
    url: ${USER_SERVICE_URL:http://user-service:8080}
  accounts-service:
    url: ${ACCOUNTS_SERVICE_URL:http://accounts-service:8080}
  transactions-service:
    url: ${TRANSACTIONS_SERVICE_URL:http://transactions-service:8080}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:banking-app-super-secret-key-change-this-in-production-256-bit}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    com.banking.apigateway: DEBUG
    org.springframework.cloud.gateway: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: ${TRACING_ENABLED:true}
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_ENDPOINT:http://jaeger:4317}

# Info endpoint
info:
  app:
    name: ${spring.application.name}
    description: Banking API Gateway
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}

# OpenTelemetry Configuration
otel:
  service:
    name: ${spring.application.name}
  exporter:
    otlp:
      protocol: http/protobuf
      endpoint: http://jaeger:4318
  traces:
    exporter: otlp
  metrics:
    exporter: otlp
  logs:
    exporter: otlp
  propagation:
    type: w3c