spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: ${services.user-service.url}
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=2
        - id: accounts-service
          uri: ${services.accounts-service.url}
          predicates:
            - Path=/api/accounts/**
          filters:
            - StripPrefix=2
        - id: transactions-service
          uri: ${services.transactions-service.url}
          predicates:
            - Path=/api/transactions/**
          filters:
            - StripPrefix=2
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      httpclient:
        connect-timeout: 30000
        response-timeout: 60s
  # Redis rate limiter configuration removed - not using rate limiting currently

server:
  port: 8080

# Service Discovery Configuration
services:
  user-service:
    url: ${USER_SERVICE_URL:http://localhost:8081}
  accounts-service:
    url: ${ACCOUNTS_SERVICE_URL:http://localhost:8082}
  transactions-service:
    url: ${TRANSACTIONS_SERVICE_URL:http://localhost:8083}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:banking-app-super-secret-key-change-this-in-production-256-bit}
  expiration: ${JWT_EXPIRATION:86400000}

# Logging Configuration
logging:
  level:
    com.banking.apigroup: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.boot.actuate.endpoint.web: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"
  file:
    name: logs/api-gateway.log
    