apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-pv.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml

