apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mysql-secret.yaml
  - mysql-configmap.yaml
  - mysql-pv.yaml
  - mysql-pvc.yaml
  - mysql-deployment.yaml
  - mysql-service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mysql
      app.kubernetes.io/instance: java-auth-mysql
      app.kubernetes.io/component: database
      app.kubernetes.io/part-of: java-auth-system
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true