server.port=${PORT:8080}
spring.main.banner-mode=off
spring.main.log-startup-info=false
logging.level.root=WARN
server.error.whitelabel.enabled=false
spring.web.resources.add-mappings=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.jmx.enabled=false
