server:
  port: 8080

spring:
  application:
    name: user-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:banking_app}
    username: ${DB_USERNAME:user_service_user}
    password: ${DB_PASSWORD:user_service_pass}
    driver-class-name: org.postgresql.Driver
    
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
      default_schema: ${DB_SCHEMA:user_service}
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DB_SCHEMA:user_service}
        
  flyway:
    schemas: ${DB_SCHEMA:user_service}
    locations: classpath:db/migration
    baseline-on-migrate: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:banking-app-super-secret-key-change-this-in-production-256-bit}
  expiration: ${JWT_EXPIRATION:86400000}

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# Logging
logging:
  level:
    com.banking.userservice: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level [%X{traceId},%X{spanId}] %logger{36} - %msg%n"