name: Java CI

on:
  push:
    branches: [ master, main ]
    paths:
      - 'java/**'
      - '.github/workflows/java-ci.yml'
  pull_request:
    branches: [ master, main ]
    paths:
      - 'java/**'
      - '.github/workflows/java-ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    
    - name: Build Java Server
      working-directory: java/server
      run: mvn clean package
    
    - name: Upload Server JAR
      uses: actions/upload-artifact@v4
      with:
        name: java-server-jar
        path: java/server/target/*.jar
        retention-days: 30
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: java-test-results
        path: java/server/target/surefire-reports/
        retention-days: 7